OPENQASM 2.0;
include "qelib1.inc";
qreg qrg_nWlrB[10];
creg qrg_nWlrB_c[10];
h qrg_nWlrB[0];
measure qrg_nWlrB[0] -> qrg_nWlrB_c[0];
h qrg_nWlrB[1];
measure qrg_nWlrB[1] -> qrg_nWlrB_c[1];
h qrg_nWlrB[2];
measure qrg_nWlrB[2] -> qrg_nWlrB_c[2];
h qrg_nWlrB[3];
measure qrg_nWlrB[3] -> qrg_nWlrB_c[3];
h qrg_nWlrB[4];
measure qrg_nWlrB[4] -> qrg_nWlrB_c[4];
h qrg_nWlrB[5];
measure qrg_nWlrB[5] -> qrg_nWlrB_c[5];
h qrg_nWlrB[6];
measure qrg_nWlrB[6] -> qrg_nWlrB_c[6];
h qrg_nWlrB[7];
measure qrg_nWlrB[7] -> qrg_nWlrB_c[7];
h qrg_nWlrB[8];
measure qrg_nWlrB[8] -> qrg_nWlrB_c[8];
h qrg_nWlrB[9];
measure qrg_nWlrB[9] -> qrg_nWlrB_c[9];
