OPENQASM 2.0;
include "qelib1.inc";
qreg qrg_nWlrB[15];
creg qrg_nWlrB_c[15];
swap qrg_nWlrB[5], qrg_nWlrB[14];
swap qrg_nWlrB[4], qrg_nWlrB[13];
swap qrg_nWlrB[3], qrg_nWlrB[12];
swap qrg_nWlrB[2], qrg_nWlrB[11];
swap qrg_nWlrB[1], qrg_nWlrB[10];
swap qrg_nWlrB[0], qrg_nWlrB[9];
x qrg_nWlrB[14];
h qrg_nWlrB[9];
h qrg_nWlrB[10];
h qrg_nWlrB[11];
h qrg_nWlrB[12];
h qrg_nWlrB[13];
x qrg_nWlrB[13];
x qrg_nWlrB[9];
x qrg_nWlrB[10];
h qrg_nWlrB[6];
CX qrg_nWlrB[10], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[6];
t qrg_nWlrB[6];
CX qrg_nWlrB[10], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[6];
t qrg_nWlrB[10];
t qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[10];
t qrg_nWlrB[9];
tdg qrg_nWlrB[10];
CX qrg_nWlrB[9], qrg_nWlrB[10];
h qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[7];
t qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[7];
t qrg_nWlrB[6];
t qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[6];
t qrg_nWlrB[11];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[11], qrg_nWlrB[6];
h qrg_nWlrB[8];
CX qrg_nWlrB[7], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[12], qrg_nWlrB[8];
t qrg_nWlrB[8];
CX qrg_nWlrB[7], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[12], qrg_nWlrB[8];
t qrg_nWlrB[7];
t qrg_nWlrB[8];
h qrg_nWlrB[8];
CX qrg_nWlrB[12], qrg_nWlrB[7];
t qrg_nWlrB[12];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[12], qrg_nWlrB[7];
h qrg_nWlrB[14];
h qrg_nWlrB[14];
CX qrg_nWlrB[8], qrg_nWlrB[14];
tdg qrg_nWlrB[14];
CX qrg_nWlrB[13], qrg_nWlrB[14];
t qrg_nWlrB[14];
CX qrg_nWlrB[8], qrg_nWlrB[14];
tdg qrg_nWlrB[14];
CX qrg_nWlrB[13], qrg_nWlrB[14];
t qrg_nWlrB[8];
t qrg_nWlrB[14];
h qrg_nWlrB[14];
CX qrg_nWlrB[13], qrg_nWlrB[8];
t qrg_nWlrB[13];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[13], qrg_nWlrB[8];
h qrg_nWlrB[8];
CX qrg_nWlrB[7], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[12], qrg_nWlrB[8];
t qrg_nWlrB[8];
CX qrg_nWlrB[7], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[12], qrg_nWlrB[8];
t qrg_nWlrB[7];
t qrg_nWlrB[8];
h qrg_nWlrB[8];
CX qrg_nWlrB[12], qrg_nWlrB[7];
t qrg_nWlrB[12];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[12], qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[7];
t qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[7];
t qrg_nWlrB[6];
t qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[6];
t qrg_nWlrB[11];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[11], qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[10], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[6];
t qrg_nWlrB[6];
CX qrg_nWlrB[10], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[6];
t qrg_nWlrB[10];
t qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[10];
t qrg_nWlrB[9];
tdg qrg_nWlrB[10];
CX qrg_nWlrB[9], qrg_nWlrB[10];
x qrg_nWlrB[13];
x qrg_nWlrB[9];
x qrg_nWlrB[10];
h qrg_nWlrB[9];
h qrg_nWlrB[10];
h qrg_nWlrB[11];
h qrg_nWlrB[12];
h qrg_nWlrB[13];
x qrg_nWlrB[13];
x qrg_nWlrB[9];
x qrg_nWlrB[10];
x qrg_nWlrB[11];
x qrg_nWlrB[12];
h qrg_nWlrB[6];
CX qrg_nWlrB[10], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[6];
t qrg_nWlrB[6];
CX qrg_nWlrB[10], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[6];
t qrg_nWlrB[10];
t qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[10];
t qrg_nWlrB[9];
tdg qrg_nWlrB[10];
CX qrg_nWlrB[9], qrg_nWlrB[10];
h qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[7];
t qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[7];
t qrg_nWlrB[6];
t qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[6];
t qrg_nWlrB[11];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[11], qrg_nWlrB[6];
h qrg_nWlrB[13];
CX qrg_nWlrB[7], qrg_nWlrB[13];
tdg qrg_nWlrB[13];
CX qrg_nWlrB[12], qrg_nWlrB[13];
t qrg_nWlrB[13];
CX qrg_nWlrB[7], qrg_nWlrB[13];
tdg qrg_nWlrB[13];
CX qrg_nWlrB[12], qrg_nWlrB[13];
t qrg_nWlrB[7];
t qrg_nWlrB[13];
h qrg_nWlrB[13];
CX qrg_nWlrB[12], qrg_nWlrB[7];
t qrg_nWlrB[12];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[12], qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[7];
t qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[7];
t qrg_nWlrB[6];
t qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[6];
t qrg_nWlrB[11];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[11], qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[10], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[6];
t qrg_nWlrB[6];
CX qrg_nWlrB[10], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[6];
t qrg_nWlrB[10];
t qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[10];
t qrg_nWlrB[9];
tdg qrg_nWlrB[10];
CX qrg_nWlrB[9], qrg_nWlrB[10];
x qrg_nWlrB[13];
x qrg_nWlrB[9];
x qrg_nWlrB[10];
x qrg_nWlrB[11];
x qrg_nWlrB[12];
h qrg_nWlrB[9];
h qrg_nWlrB[10];
h qrg_nWlrB[11];
h qrg_nWlrB[12];
h qrg_nWlrB[13];
x qrg_nWlrB[13];
x qrg_nWlrB[9];
x qrg_nWlrB[10];
h qrg_nWlrB[6];
CX qrg_nWlrB[10], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[6];
t qrg_nWlrB[6];
CX qrg_nWlrB[10], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[6];
t qrg_nWlrB[10];
t qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[10];
t qrg_nWlrB[9];
tdg qrg_nWlrB[10];
CX qrg_nWlrB[9], qrg_nWlrB[10];
h qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[7];
t qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[7];
t qrg_nWlrB[6];
t qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[6];
t qrg_nWlrB[11];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[11], qrg_nWlrB[6];
h qrg_nWlrB[8];
CX qrg_nWlrB[7], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[12], qrg_nWlrB[8];
t qrg_nWlrB[8];
CX qrg_nWlrB[7], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[12], qrg_nWlrB[8];
t qrg_nWlrB[7];
t qrg_nWlrB[8];
h qrg_nWlrB[8];
CX qrg_nWlrB[12], qrg_nWlrB[7];
t qrg_nWlrB[12];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[12], qrg_nWlrB[7];
h qrg_nWlrB[14];
CX qrg_nWlrB[8], qrg_nWlrB[14];
tdg qrg_nWlrB[14];
CX qrg_nWlrB[13], qrg_nWlrB[14];
t qrg_nWlrB[14];
CX qrg_nWlrB[8], qrg_nWlrB[14];
tdg qrg_nWlrB[14];
CX qrg_nWlrB[13], qrg_nWlrB[14];
t qrg_nWlrB[8];
t qrg_nWlrB[14];
h qrg_nWlrB[14];
CX qrg_nWlrB[13], qrg_nWlrB[8];
t qrg_nWlrB[13];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[13], qrg_nWlrB[8];
h qrg_nWlrB[8];
CX qrg_nWlrB[7], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[12], qrg_nWlrB[8];
t qrg_nWlrB[8];
CX qrg_nWlrB[7], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[12], qrg_nWlrB[8];
t qrg_nWlrB[7];
t qrg_nWlrB[8];
h qrg_nWlrB[8];
CX qrg_nWlrB[12], qrg_nWlrB[7];
t qrg_nWlrB[12];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[12], qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[7];
t qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[7];
t qrg_nWlrB[6];
t qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[6];
t qrg_nWlrB[11];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[11], qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[10], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[6];
t qrg_nWlrB[6];
CX qrg_nWlrB[10], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[6];
t qrg_nWlrB[10];
t qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[10];
t qrg_nWlrB[9];
tdg qrg_nWlrB[10];
CX qrg_nWlrB[9], qrg_nWlrB[10];
x qrg_nWlrB[13];
x qrg_nWlrB[9];
x qrg_nWlrB[10];
h qrg_nWlrB[9];
h qrg_nWlrB[10];
h qrg_nWlrB[11];
h qrg_nWlrB[12];
h qrg_nWlrB[13];
x qrg_nWlrB[13];
x qrg_nWlrB[9];
x qrg_nWlrB[10];
x qrg_nWlrB[11];
x qrg_nWlrB[12];
h qrg_nWlrB[6];
CX qrg_nWlrB[10], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[6];
t qrg_nWlrB[6];
CX qrg_nWlrB[10], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[6];
t qrg_nWlrB[10];
t qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[10];
t qrg_nWlrB[9];
tdg qrg_nWlrB[10];
CX qrg_nWlrB[9], qrg_nWlrB[10];
h qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[7];
t qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[7];
t qrg_nWlrB[6];
t qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[6];
t qrg_nWlrB[11];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[11], qrg_nWlrB[6];
h qrg_nWlrB[13];
CX qrg_nWlrB[7], qrg_nWlrB[13];
tdg qrg_nWlrB[13];
CX qrg_nWlrB[12], qrg_nWlrB[13];
t qrg_nWlrB[13];
CX qrg_nWlrB[7], qrg_nWlrB[13];
tdg qrg_nWlrB[13];
CX qrg_nWlrB[12], qrg_nWlrB[13];
t qrg_nWlrB[7];
t qrg_nWlrB[13];
h qrg_nWlrB[13];
CX qrg_nWlrB[12], qrg_nWlrB[7];
t qrg_nWlrB[12];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[12], qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[7];
t qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[7];
t qrg_nWlrB[6];
t qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[6];
t qrg_nWlrB[11];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[11], qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[10], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[6];
t qrg_nWlrB[6];
CX qrg_nWlrB[10], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[6];
t qrg_nWlrB[10];
t qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[10];
t qrg_nWlrB[9];
tdg qrg_nWlrB[10];
CX qrg_nWlrB[9], qrg_nWlrB[10];
x qrg_nWlrB[13];
x qrg_nWlrB[9];
x qrg_nWlrB[10];
x qrg_nWlrB[11];
x qrg_nWlrB[12];
h qrg_nWlrB[9];
h qrg_nWlrB[10];
h qrg_nWlrB[11];
h qrg_nWlrB[12];
h qrg_nWlrB[13];
x qrg_nWlrB[13];
x qrg_nWlrB[9];
x qrg_nWlrB[10];
h qrg_nWlrB[6];
CX qrg_nWlrB[10], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[6];
t qrg_nWlrB[6];
CX qrg_nWlrB[10], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[6];
t qrg_nWlrB[10];
t qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[10];
t qrg_nWlrB[9];
tdg qrg_nWlrB[10];
CX qrg_nWlrB[9], qrg_nWlrB[10];
h qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[7];
t qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[7];
t qrg_nWlrB[6];
t qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[6];
t qrg_nWlrB[11];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[11], qrg_nWlrB[6];
h qrg_nWlrB[8];
CX qrg_nWlrB[7], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[12], qrg_nWlrB[8];
t qrg_nWlrB[8];
CX qrg_nWlrB[7], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[12], qrg_nWlrB[8];
t qrg_nWlrB[7];
t qrg_nWlrB[8];
h qrg_nWlrB[8];
CX qrg_nWlrB[12], qrg_nWlrB[7];
t qrg_nWlrB[12];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[12], qrg_nWlrB[7];
h qrg_nWlrB[14];
CX qrg_nWlrB[8], qrg_nWlrB[14];
tdg qrg_nWlrB[14];
CX qrg_nWlrB[13], qrg_nWlrB[14];
t qrg_nWlrB[14];
CX qrg_nWlrB[8], qrg_nWlrB[14];
tdg qrg_nWlrB[14];
CX qrg_nWlrB[13], qrg_nWlrB[14];
t qrg_nWlrB[8];
t qrg_nWlrB[14];
h qrg_nWlrB[14];
CX qrg_nWlrB[13], qrg_nWlrB[8];
t qrg_nWlrB[13];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[13], qrg_nWlrB[8];
h qrg_nWlrB[8];
CX qrg_nWlrB[7], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[12], qrg_nWlrB[8];
t qrg_nWlrB[8];
CX qrg_nWlrB[7], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[12], qrg_nWlrB[8];
t qrg_nWlrB[7];
t qrg_nWlrB[8];
h qrg_nWlrB[8];
CX qrg_nWlrB[12], qrg_nWlrB[7];
t qrg_nWlrB[12];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[12], qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[7];
t qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[7];
t qrg_nWlrB[6];
t qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[6];
t qrg_nWlrB[11];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[11], qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[10], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[6];
t qrg_nWlrB[6];
CX qrg_nWlrB[10], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[6];
t qrg_nWlrB[10];
t qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[10];
t qrg_nWlrB[9];
tdg qrg_nWlrB[10];
CX qrg_nWlrB[9], qrg_nWlrB[10];
x qrg_nWlrB[13];
x qrg_nWlrB[9];
x qrg_nWlrB[10];
h qrg_nWlrB[9];
h qrg_nWlrB[10];
h qrg_nWlrB[11];
h qrg_nWlrB[12];
h qrg_nWlrB[13];
x qrg_nWlrB[13];
x qrg_nWlrB[9];
x qrg_nWlrB[10];
x qrg_nWlrB[11];
x qrg_nWlrB[12];
h qrg_nWlrB[6];
CX qrg_nWlrB[10], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[6];
t qrg_nWlrB[6];
CX qrg_nWlrB[10], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[6];
t qrg_nWlrB[10];
t qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[10];
t qrg_nWlrB[9];
tdg qrg_nWlrB[10];
CX qrg_nWlrB[9], qrg_nWlrB[10];
h qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[7];
t qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[7];
t qrg_nWlrB[6];
t qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[6];
t qrg_nWlrB[11];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[11], qrg_nWlrB[6];
h qrg_nWlrB[13];
CX qrg_nWlrB[7], qrg_nWlrB[13];
tdg qrg_nWlrB[13];
CX qrg_nWlrB[12], qrg_nWlrB[13];
t qrg_nWlrB[13];
CX qrg_nWlrB[7], qrg_nWlrB[13];
tdg qrg_nWlrB[13];
CX qrg_nWlrB[12], qrg_nWlrB[13];
t qrg_nWlrB[7];
t qrg_nWlrB[13];
h qrg_nWlrB[13];
CX qrg_nWlrB[12], qrg_nWlrB[7];
t qrg_nWlrB[12];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[12], qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[7];
t qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[7];
t qrg_nWlrB[6];
t qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[6];
t qrg_nWlrB[11];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[11], qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[10], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[6];
t qrg_nWlrB[6];
CX qrg_nWlrB[10], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[6];
t qrg_nWlrB[10];
t qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[10];
t qrg_nWlrB[9];
tdg qrg_nWlrB[10];
CX qrg_nWlrB[9], qrg_nWlrB[10];
x qrg_nWlrB[13];
x qrg_nWlrB[9];
x qrg_nWlrB[10];
x qrg_nWlrB[11];
x qrg_nWlrB[12];
h qrg_nWlrB[9];
h qrg_nWlrB[10];
h qrg_nWlrB[11];
h qrg_nWlrB[12];
h qrg_nWlrB[13];
x qrg_nWlrB[13];
x qrg_nWlrB[9];
x qrg_nWlrB[10];
h qrg_nWlrB[6];
CX qrg_nWlrB[10], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[6];
t qrg_nWlrB[6];
CX qrg_nWlrB[10], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[6];
t qrg_nWlrB[10];
t qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[10];
t qrg_nWlrB[9];
tdg qrg_nWlrB[10];
CX qrg_nWlrB[9], qrg_nWlrB[10];
h qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[7];
t qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[7];
t qrg_nWlrB[6];
t qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[6];
t qrg_nWlrB[11];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[11], qrg_nWlrB[6];
h qrg_nWlrB[8];
CX qrg_nWlrB[7], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[12], qrg_nWlrB[8];
t qrg_nWlrB[8];
CX qrg_nWlrB[7], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[12], qrg_nWlrB[8];
t qrg_nWlrB[7];
t qrg_nWlrB[8];
h qrg_nWlrB[8];
CX qrg_nWlrB[12], qrg_nWlrB[7];
t qrg_nWlrB[12];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[12], qrg_nWlrB[7];
h qrg_nWlrB[14];
CX qrg_nWlrB[8], qrg_nWlrB[14];
tdg qrg_nWlrB[14];
CX qrg_nWlrB[13], qrg_nWlrB[14];
t qrg_nWlrB[14];
CX qrg_nWlrB[8], qrg_nWlrB[14];
tdg qrg_nWlrB[14];
CX qrg_nWlrB[13], qrg_nWlrB[14];
t qrg_nWlrB[8];
t qrg_nWlrB[14];
h qrg_nWlrB[14];
CX qrg_nWlrB[13], qrg_nWlrB[8];
t qrg_nWlrB[13];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[13], qrg_nWlrB[8];
h qrg_nWlrB[8];
CX qrg_nWlrB[7], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[12], qrg_nWlrB[8];
t qrg_nWlrB[8];
CX qrg_nWlrB[7], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[12], qrg_nWlrB[8];
t qrg_nWlrB[7];
t qrg_nWlrB[8];
h qrg_nWlrB[8];
CX qrg_nWlrB[12], qrg_nWlrB[7];
t qrg_nWlrB[12];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[12], qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[7];
t qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[7];
t qrg_nWlrB[6];
t qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[6];
t qrg_nWlrB[11];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[11], qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[10], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[6];
t qrg_nWlrB[6];
CX qrg_nWlrB[10], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[6];
t qrg_nWlrB[10];
t qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[10];
t qrg_nWlrB[9];
tdg qrg_nWlrB[10];
CX qrg_nWlrB[9], qrg_nWlrB[10];
x qrg_nWlrB[13];
x qrg_nWlrB[9];
x qrg_nWlrB[10];
h qrg_nWlrB[9];
h qrg_nWlrB[10];
h qrg_nWlrB[11];
h qrg_nWlrB[12];
h qrg_nWlrB[13];
x qrg_nWlrB[13];
x qrg_nWlrB[9];
x qrg_nWlrB[10];
x qrg_nWlrB[11];
x qrg_nWlrB[12];
h qrg_nWlrB[6];
CX qrg_nWlrB[10], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[6];
t qrg_nWlrB[6];
CX qrg_nWlrB[10], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[6];
t qrg_nWlrB[10];
t qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[10];
t qrg_nWlrB[9];
tdg qrg_nWlrB[10];
CX qrg_nWlrB[9], qrg_nWlrB[10];
h qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[7];
t qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[7];
t qrg_nWlrB[6];
t qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[6];
t qrg_nWlrB[11];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[11], qrg_nWlrB[6];
h qrg_nWlrB[13];
CX qrg_nWlrB[7], qrg_nWlrB[13];
tdg qrg_nWlrB[13];
CX qrg_nWlrB[12], qrg_nWlrB[13];
t qrg_nWlrB[13];
CX qrg_nWlrB[7], qrg_nWlrB[13];
tdg qrg_nWlrB[13];
CX qrg_nWlrB[12], qrg_nWlrB[13];
t qrg_nWlrB[7];
t qrg_nWlrB[13];
h qrg_nWlrB[13];
CX qrg_nWlrB[12], qrg_nWlrB[7];
t qrg_nWlrB[12];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[12], qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[7];
t qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[7];
t qrg_nWlrB[6];
t qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[11], qrg_nWlrB[6];
t qrg_nWlrB[11];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[11], qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[10], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[6];
t qrg_nWlrB[6];
CX qrg_nWlrB[10], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[6];
t qrg_nWlrB[10];
t qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[9], qrg_nWlrB[10];
t qrg_nWlrB[9];
tdg qrg_nWlrB[10];
CX qrg_nWlrB[9], qrg_nWlrB[10];
x qrg_nWlrB[13];
x qrg_nWlrB[9];
x qrg_nWlrB[10];
x qrg_nWlrB[11];
x qrg_nWlrB[12];
h qrg_nWlrB[9];
h qrg_nWlrB[10];
h qrg_nWlrB[11];
h qrg_nWlrB[12];
h qrg_nWlrB[13];
swap qrg_nWlrB[0], qrg_nWlrB[9];
swap qrg_nWlrB[1], qrg_nWlrB[10];
swap qrg_nWlrB[2], qrg_nWlrB[11];
swap qrg_nWlrB[3], qrg_nWlrB[12];
swap qrg_nWlrB[4], qrg_nWlrB[13];
swap qrg_nWlrB[5], qrg_nWlrB[14];
