OPENQASM 2.0;
include "qelib1.inc";
qreg qrg_nWlrB[9];
creg qrg_nWlrB_c[9];
x qrg_nWlrB[5];
h qrg_nWlrB[0];
h qrg_nWlrB[1];
h qrg_nWlrB[2];
h qrg_nWlrB[3];
h qrg_nWlrB[4];
x qrg_nWlrB[4];
x qrg_nWlrB[0];
x qrg_nWlrB[1];
h qrg_nWlrB[6];
CX qrg_nWlrB[1], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[0], qrg_nWlrB[6];
t qrg_nWlrB[6];
CX qrg_nWlrB[1], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[0], qrg_nWlrB[6];
t qrg_nWlrB[6];
h qrg_nWlrB[6];
h qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[2], qrg_nWlrB[7];
t qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[2], qrg_nWlrB[7];
t qrg_nWlrB[7];
h qrg_nWlrB[7];
h qrg_nWlrB[8];
CX qrg_nWlrB[7], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[3], qrg_nWlrB[8];
t qrg_nWlrB[8];
CX qrg_nWlrB[7], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[3], qrg_nWlrB[8];
t qrg_nWlrB[8];
h qrg_nWlrB[8];
CX qrg_nWlrB[8], qrg_nWlrB[5];
tdg qrg_nWlrB[5];
CX qrg_nWlrB[4], qrg_nWlrB[5];
t qrg_nWlrB[5];
CX qrg_nWlrB[8], qrg_nWlrB[5];
CX qrg_nWlrB[4], qrg_nWlrB[5];
t qrg_nWlrB[8];
CX qrg_nWlrB[4], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[4], qrg_nWlrB[8];
h qrg_nWlrB[8];
CX qrg_nWlrB[7], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[3], qrg_nWlrB[8];
t qrg_nWlrB[8];
CX qrg_nWlrB[7], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[3], qrg_nWlrB[8];
rz(-4.7123889803846897) qrg_nWlrB[7];
CX qrg_nWlrB[3], qrg_nWlrB[7];
s qrg_nWlrB[3];
sdg qrg_nWlrB[7];
CX qrg_nWlrB[3], qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[2], qrg_nWlrB[7];
t qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[2], qrg_nWlrB[7];
s qrg_nWlrB[6];
CX qrg_nWlrB[2], qrg_nWlrB[6];
s qrg_nWlrB[2];
sdg qrg_nWlrB[6];
CX qrg_nWlrB[2], qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[1], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[0], qrg_nWlrB[6];
t qrg_nWlrB[6];
CX qrg_nWlrB[1], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[0], qrg_nWlrB[6];
s qrg_nWlrB[1];
CX qrg_nWlrB[0], qrg_nWlrB[1];
s qrg_nWlrB[0];
sdg qrg_nWlrB[1];
CX qrg_nWlrB[0], qrg_nWlrB[1];
rx(3.1415926535897931) qrg_nWlrB[4];
rz(9.4247779607693793) qrg_nWlrB[4];
x qrg_nWlrB[0];
x qrg_nWlrB[1];
h qrg_nWlrB[0];
h qrg_nWlrB[1];
h qrg_nWlrB[2];
h qrg_nWlrB[3];
x qrg_nWlrB[0];
x qrg_nWlrB[1];
x qrg_nWlrB[2];
x qrg_nWlrB[3];
CX qrg_nWlrB[1], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[0], qrg_nWlrB[6];
t qrg_nWlrB[6];
CX qrg_nWlrB[1], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[0], qrg_nWlrB[6];
s qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[2], qrg_nWlrB[7];
t qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[2], qrg_nWlrB[7];
s qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[7], qrg_nWlrB[4];
tdg qrg_nWlrB[4];
CX qrg_nWlrB[3], qrg_nWlrB[4];
t qrg_nWlrB[4];
CX qrg_nWlrB[7], qrg_nWlrB[4];
tdg qrg_nWlrB[4];
CX qrg_nWlrB[3], qrg_nWlrB[4];
t qrg_nWlrB[7];
rx(3.1415926535897931) qrg_nWlrB[4];
rz(3.1415926535897931) qrg_nWlrB[4];
CX qrg_nWlrB[3], qrg_nWlrB[7];
t qrg_nWlrB[3];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[3], qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[2], qrg_nWlrB[7];
t qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[2], qrg_nWlrB[7];
s qrg_nWlrB[6];
CX qrg_nWlrB[2], qrg_nWlrB[6];
s qrg_nWlrB[2];
sdg qrg_nWlrB[6];
CX qrg_nWlrB[2], qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[1], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[0], qrg_nWlrB[6];
t qrg_nWlrB[6];
CX qrg_nWlrB[1], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[0], qrg_nWlrB[6];
s qrg_nWlrB[1];
CX qrg_nWlrB[0], qrg_nWlrB[1];
s qrg_nWlrB[0];
sdg qrg_nWlrB[1];
CX qrg_nWlrB[0], qrg_nWlrB[1];
x qrg_nWlrB[0];
x qrg_nWlrB[1];
ry(-1.5707963267948970) qrg_nWlrB[2];
ry(-1.5707963267948970) qrg_nWlrB[3];
h qrg_nWlrB[0];
h qrg_nWlrB[1];
x qrg_nWlrB[0];
x qrg_nWlrB[1];
CX qrg_nWlrB[1], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[0], qrg_nWlrB[6];
t qrg_nWlrB[6];
CX qrg_nWlrB[1], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[0], qrg_nWlrB[6];
s qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[2], qrg_nWlrB[7];
t qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[2], qrg_nWlrB[7];
s qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[7], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[3], qrg_nWlrB[8];
t qrg_nWlrB[8];
CX qrg_nWlrB[7], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[3], qrg_nWlrB[8];
s qrg_nWlrB[8];
h qrg_nWlrB[8];
CX qrg_nWlrB[8], qrg_nWlrB[5];
tdg qrg_nWlrB[5];
CX qrg_nWlrB[4], qrg_nWlrB[5];
t qrg_nWlrB[5];
CX qrg_nWlrB[8], qrg_nWlrB[5];
sdg qrg_nWlrB[5];
CX qrg_nWlrB[4], qrg_nWlrB[5];
t qrg_nWlrB[8];
s qrg_nWlrB[5];
CX qrg_nWlrB[4], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[4], qrg_nWlrB[8];
h qrg_nWlrB[8];
CX qrg_nWlrB[7], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[3], qrg_nWlrB[8];
t qrg_nWlrB[8];
CX qrg_nWlrB[7], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[3], qrg_nWlrB[8];
s qrg_nWlrB[7];
CX qrg_nWlrB[3], qrg_nWlrB[7];
s qrg_nWlrB[3];
sdg qrg_nWlrB[7];
CX qrg_nWlrB[3], qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[2], qrg_nWlrB[7];
t qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[2], qrg_nWlrB[7];
s qrg_nWlrB[6];
CX qrg_nWlrB[2], qrg_nWlrB[6];
s qrg_nWlrB[2];
sdg qrg_nWlrB[6];
CX qrg_nWlrB[2], qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[1], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[0], qrg_nWlrB[6];
t qrg_nWlrB[6];
CX qrg_nWlrB[1], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[0], qrg_nWlrB[6];
s qrg_nWlrB[1];
CX qrg_nWlrB[0], qrg_nWlrB[1];
s qrg_nWlrB[0];
sdg qrg_nWlrB[1];
CX qrg_nWlrB[0], qrg_nWlrB[1];
rx(3.1415926535897931) qrg_nWlrB[4];
rz(9.4247779607693793) qrg_nWlrB[4];
x qrg_nWlrB[0];
x qrg_nWlrB[1];
h qrg_nWlrB[0];
h qrg_nWlrB[1];
h qrg_nWlrB[2];
h qrg_nWlrB[3];
x qrg_nWlrB[0];
x qrg_nWlrB[1];
x qrg_nWlrB[2];
x qrg_nWlrB[3];
CX qrg_nWlrB[1], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[0], qrg_nWlrB[6];
t qrg_nWlrB[6];
CX qrg_nWlrB[1], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[0], qrg_nWlrB[6];
s qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[2], qrg_nWlrB[7];
t qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[2], qrg_nWlrB[7];
s qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[7], qrg_nWlrB[4];
tdg qrg_nWlrB[4];
CX qrg_nWlrB[3], qrg_nWlrB[4];
t qrg_nWlrB[4];
CX qrg_nWlrB[7], qrg_nWlrB[4];
tdg qrg_nWlrB[4];
CX qrg_nWlrB[3], qrg_nWlrB[4];
t qrg_nWlrB[7];
rx(3.1415926535897931) qrg_nWlrB[4];
rz(3.1415926535897931) qrg_nWlrB[4];
CX qrg_nWlrB[3], qrg_nWlrB[7];
t qrg_nWlrB[3];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[3], qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[2], qrg_nWlrB[7];
t qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[2], qrg_nWlrB[7];
s qrg_nWlrB[6];
CX qrg_nWlrB[2], qrg_nWlrB[6];
s qrg_nWlrB[2];
sdg qrg_nWlrB[6];
CX qrg_nWlrB[2], qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[1], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[0], qrg_nWlrB[6];
t qrg_nWlrB[6];
CX qrg_nWlrB[1], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[0], qrg_nWlrB[6];
s qrg_nWlrB[1];
CX qrg_nWlrB[0], qrg_nWlrB[1];
s qrg_nWlrB[0];
sdg qrg_nWlrB[1];
CX qrg_nWlrB[0], qrg_nWlrB[1];
x qrg_nWlrB[0];
x qrg_nWlrB[1];
ry(-1.5707963267948970) qrg_nWlrB[2];
ry(-1.5707963267948970) qrg_nWlrB[3];
h qrg_nWlrB[0];
h qrg_nWlrB[1];
x qrg_nWlrB[0];
x qrg_nWlrB[1];
CX qrg_nWlrB[1], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[0], qrg_nWlrB[6];
t qrg_nWlrB[6];
CX qrg_nWlrB[1], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[0], qrg_nWlrB[6];
s qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[2], qrg_nWlrB[7];
t qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[2], qrg_nWlrB[7];
s qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[7], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[3], qrg_nWlrB[8];
t qrg_nWlrB[8];
CX qrg_nWlrB[7], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[3], qrg_nWlrB[8];
s qrg_nWlrB[8];
h qrg_nWlrB[8];
CX qrg_nWlrB[8], qrg_nWlrB[5];
tdg qrg_nWlrB[5];
CX qrg_nWlrB[4], qrg_nWlrB[5];
t qrg_nWlrB[5];
CX qrg_nWlrB[8], qrg_nWlrB[5];
CX qrg_nWlrB[4], qrg_nWlrB[5];
t qrg_nWlrB[8];
CX qrg_nWlrB[4], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[4], qrg_nWlrB[8];
h qrg_nWlrB[8];
CX qrg_nWlrB[7], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[3], qrg_nWlrB[8];
t qrg_nWlrB[8];
CX qrg_nWlrB[7], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[3], qrg_nWlrB[8];
s qrg_nWlrB[7];
CX qrg_nWlrB[3], qrg_nWlrB[7];
s qrg_nWlrB[3];
sdg qrg_nWlrB[7];
CX qrg_nWlrB[3], qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[2], qrg_nWlrB[7];
t qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[2], qrg_nWlrB[7];
s qrg_nWlrB[6];
CX qrg_nWlrB[2], qrg_nWlrB[6];
s qrg_nWlrB[2];
sdg qrg_nWlrB[6];
CX qrg_nWlrB[2], qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[1], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[0], qrg_nWlrB[6];
t qrg_nWlrB[6];
CX qrg_nWlrB[1], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[0], qrg_nWlrB[6];
s qrg_nWlrB[1];
CX qrg_nWlrB[0], qrg_nWlrB[1];
s qrg_nWlrB[0];
sdg qrg_nWlrB[1];
CX qrg_nWlrB[0], qrg_nWlrB[1];
rx(3.1415926535897931) qrg_nWlrB[4];
rz(9.4247779607693793) qrg_nWlrB[4];
x qrg_nWlrB[0];
x qrg_nWlrB[1];
h qrg_nWlrB[0];
h qrg_nWlrB[1];
h qrg_nWlrB[2];
h qrg_nWlrB[3];
x qrg_nWlrB[0];
x qrg_nWlrB[1];
x qrg_nWlrB[2];
x qrg_nWlrB[3];
CX qrg_nWlrB[1], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[0], qrg_nWlrB[6];
t qrg_nWlrB[6];
CX qrg_nWlrB[1], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[0], qrg_nWlrB[6];
s qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[2], qrg_nWlrB[7];
t qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[2], qrg_nWlrB[7];
s qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[7], qrg_nWlrB[4];
tdg qrg_nWlrB[4];
CX qrg_nWlrB[3], qrg_nWlrB[4];
t qrg_nWlrB[4];
CX qrg_nWlrB[7], qrg_nWlrB[4];
tdg qrg_nWlrB[4];
CX qrg_nWlrB[3], qrg_nWlrB[4];
t qrg_nWlrB[7];
rx(3.1415926535897931) qrg_nWlrB[4];
rz(3.1415926535897931) qrg_nWlrB[4];
CX qrg_nWlrB[3], qrg_nWlrB[7];
t qrg_nWlrB[3];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[3], qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[2], qrg_nWlrB[7];
t qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[2], qrg_nWlrB[7];
s qrg_nWlrB[6];
CX qrg_nWlrB[2], qrg_nWlrB[6];
s qrg_nWlrB[2];
sdg qrg_nWlrB[6];
CX qrg_nWlrB[2], qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[1], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[0], qrg_nWlrB[6];
t qrg_nWlrB[6];
CX qrg_nWlrB[1], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[0], qrg_nWlrB[6];
s qrg_nWlrB[1];
CX qrg_nWlrB[0], qrg_nWlrB[1];
s qrg_nWlrB[0];
sdg qrg_nWlrB[1];
CX qrg_nWlrB[0], qrg_nWlrB[1];
x qrg_nWlrB[0];
x qrg_nWlrB[1];
ry(-1.5707963267948970) qrg_nWlrB[2];
ry(-1.5707963267948970) qrg_nWlrB[3];
h qrg_nWlrB[0];
h qrg_nWlrB[1];
x qrg_nWlrB[0];
x qrg_nWlrB[1];
CX qrg_nWlrB[1], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[0], qrg_nWlrB[6];
t qrg_nWlrB[6];
CX qrg_nWlrB[1], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[0], qrg_nWlrB[6];
s qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[2], qrg_nWlrB[7];
t qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[2], qrg_nWlrB[7];
s qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[7], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[3], qrg_nWlrB[8];
t qrg_nWlrB[8];
CX qrg_nWlrB[7], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[3], qrg_nWlrB[8];
s qrg_nWlrB[8];
h qrg_nWlrB[8];
CX qrg_nWlrB[8], qrg_nWlrB[5];
tdg qrg_nWlrB[5];
CX qrg_nWlrB[4], qrg_nWlrB[5];
t qrg_nWlrB[5];
CX qrg_nWlrB[8], qrg_nWlrB[5];
sdg qrg_nWlrB[5];
CX qrg_nWlrB[4], qrg_nWlrB[5];
t qrg_nWlrB[8];
s qrg_nWlrB[5];
h qrg_nWlrB[5];
CX qrg_nWlrB[4], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[4], qrg_nWlrB[8];
h qrg_nWlrB[8];
CX qrg_nWlrB[7], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[3], qrg_nWlrB[8];
t qrg_nWlrB[8];
CX qrg_nWlrB[7], qrg_nWlrB[8];
tdg qrg_nWlrB[8];
CX qrg_nWlrB[3], qrg_nWlrB[8];
s qrg_nWlrB[7];
t qrg_nWlrB[8];
h qrg_nWlrB[8];
CX qrg_nWlrB[3], qrg_nWlrB[7];
s qrg_nWlrB[3];
sdg qrg_nWlrB[7];
CX qrg_nWlrB[3], qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[2], qrg_nWlrB[7];
t qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[2], qrg_nWlrB[7];
s qrg_nWlrB[6];
CX qrg_nWlrB[2], qrg_nWlrB[6];
s qrg_nWlrB[2];
sdg qrg_nWlrB[6];
CX qrg_nWlrB[2], qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[1], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[0], qrg_nWlrB[6];
t qrg_nWlrB[6];
CX qrg_nWlrB[1], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[0], qrg_nWlrB[6];
s qrg_nWlrB[1];
CX qrg_nWlrB[0], qrg_nWlrB[1];
s qrg_nWlrB[0];
sdg qrg_nWlrB[1];
CX qrg_nWlrB[0], qrg_nWlrB[1];
rx(3.1415926535897931) qrg_nWlrB[4];
rz(9.4247779607693793) qrg_nWlrB[4];
x qrg_nWlrB[0];
x qrg_nWlrB[1];
h qrg_nWlrB[0];
h qrg_nWlrB[1];
h qrg_nWlrB[2];
h qrg_nWlrB[3];
x qrg_nWlrB[0];
x qrg_nWlrB[1];
x qrg_nWlrB[2];
x qrg_nWlrB[3];
CX qrg_nWlrB[1], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[0], qrg_nWlrB[6];
t qrg_nWlrB[6];
CX qrg_nWlrB[1], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[0], qrg_nWlrB[6];
s qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[2], qrg_nWlrB[7];
t qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[2], qrg_nWlrB[7];
s qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[7], qrg_nWlrB[4];
tdg qrg_nWlrB[4];
CX qrg_nWlrB[3], qrg_nWlrB[4];
t qrg_nWlrB[4];
CX qrg_nWlrB[7], qrg_nWlrB[4];
tdg qrg_nWlrB[4];
CX qrg_nWlrB[3], qrg_nWlrB[4];
t qrg_nWlrB[7];
rz(3.1415926535897931) qrg_nWlrB[4];
CX qrg_nWlrB[3], qrg_nWlrB[7];
t qrg_nWlrB[3];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[3], qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[2], qrg_nWlrB[7];
t qrg_nWlrB[7];
CX qrg_nWlrB[6], qrg_nWlrB[7];
tdg qrg_nWlrB[7];
CX qrg_nWlrB[2], qrg_nWlrB[7];
s qrg_nWlrB[6];
t qrg_nWlrB[7];
h qrg_nWlrB[7];
CX qrg_nWlrB[2], qrg_nWlrB[6];
s qrg_nWlrB[2];
sdg qrg_nWlrB[6];
CX qrg_nWlrB[2], qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[1], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[0], qrg_nWlrB[6];
t qrg_nWlrB[6];
CX qrg_nWlrB[1], qrg_nWlrB[6];
tdg qrg_nWlrB[6];
CX qrg_nWlrB[0], qrg_nWlrB[6];
s qrg_nWlrB[1];
t qrg_nWlrB[6];
h qrg_nWlrB[6];
CX qrg_nWlrB[0], qrg_nWlrB[1];
s qrg_nWlrB[0];
sdg qrg_nWlrB[1];
CX qrg_nWlrB[0], qrg_nWlrB[1];
ry(-1.5707963267948970) qrg_nWlrB[0];
ry(-1.5707963267948970) qrg_nWlrB[1];
ry(-1.5707963267948970) qrg_nWlrB[2];
ry(-1.5707963267948970) qrg_nWlrB[3];
